# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cresterida
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-heroe
frameworkVersion: '4'

stages:
    dev:
        name: development
        description: Development stage
    prod:
        name: production
        description: Production stage
provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  profile: ${opt:aws-profile, 'default'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListAllMyBuckets
            - sts:GetCallerIdentity
          Resource: '*'

custom:
  pythonRequirements:
    layer: true
    zip: false
  userPoolName: ${self:service}-${self:provider.stage}-user-pool
  userPoolClientName: ${self:service}-${self:provider.stage}-client
  identityPoolName: ${self:service}-${self:provider.stage}-identity-pool

package:
  individually: true

functions:
  hello:
    name: ${self:stages.dev.name}-${self:service}-hello
    handler: lambdas/handler.hello
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /
          method: get
    package:
      exclude:
        - '**'
      include:
        - lambdas/handler.py
        - lib/response.py
  returnHtml:
    name: ${self:stages.dev.name}-${self:service}-returnHtml
    handler: lambdas/handler.returnHtml
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /html
          method: get
    package:
      exclude:
        - '**'
      include:
        - lambdas/handler.py
        - lib/response.py
        - static/index.html
plugins:
  - serverless-python-requirements

resources:
  Resources:

