# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cresterida
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-heroe
frameworkVersion: '4'

stages:
    dev:
        name: development
        description: Development stage
    prod:
        name: production
        description: Production stage
provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  profile: ${opt:aws-profile, 'default'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListAllMyBuckets
            - sts:GetCallerIdentity
          Resource: '*'

custom:
  pythonRequirements:
    layer: true
    zip: false

package:
  individually: true

functions:
  get-restaurants:
    handler: restaurants.handler
    name: ${self:stages.${self:provider.stage}.name}-get-restaurants
    events:
      - http:
          path: /restaurants
          method: get
          cors: true
    package:
      exclude:
        - '**'
      include:
        - lambda/restaurants.py
        - lib/response.py
resources:
  Resources:
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.restaurants_table}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
