# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cresterida
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-heroe
frameworkVersion: '4'

stages:
    dev:
        name: development
        description: Development stage
        RESTAURANT_TABLE: ${self:stages.dev.name}-${self:service}-restaurants
    prod:
        name: production
        description: Production stage
provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  profile: ${opt:aws-profile, 'default'}
  logRetentionInDays: 7
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListAllMyBuckets
            - sts:GetCallerIdentity
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:Query
          Resource: !GetAtt RestaurantsTable.Arn
        - Effect: Allow
          Action:
            - execute-api:Invoke
          Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/${self:provider.stage}/GET/restaurants'
custom:
  pythonRequirements:
    layer: true

package:
  individually: true

functions:
  index:
    handler: lambdas/restaurants.load_restaurants
    name: ${self:stages.${self:provider.stage}.name}-index
    events:
      - http:
          path: /
          method: get
          cors: true
    package:
        exclude:
            - '**'
        include:
            - lambdas/restaurants.py
            - lib/response.py
            - static/index.html
    layers:
      - Ref: PythonRequirementsLambdaLayer
    environment:
      default_results: 8
      RESTAURANTS_TABLE: ${self:stages.${self:provider.stage}.RESTAURANT_TABLE}
      API_GATEWAY: !Sub 'https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${self:provider.stage}'

  get-restaurants:
    handler: lambdas/restaurants.handler
    name: ${self:stages.${self:provider.stage}.name}-get-restaurants
    environment:
      RESTAURANTS_TABLE: ${self:stages.${self:provider.stage}.RESTAURANT_TABLE}
      default_results: 8
    events:
      - http:
          path: /restaurants
          method: get
          cors: true
    package:
      exclude:
        - '**'
      include:
        - lambdas/restaurants.py
        - lib/response.py
    layers:
      - Ref: PythonRequirementsLambdaLayer
plugins:
  - serverless-python-requirements
resources:
  Resources:
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:stages.${self:provider.stage}.RESTAURANT_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
