# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cresterida
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-heroe
frameworkVersion: '4'

stages:
    dev:
        name: development
        description: Development stage
        RESTAURANT_TABLE: ${self:service}-${self:provider.stage}-restaurants
    prod:
        name: production
        description: Production stage
provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  profile: ${opt:aws-profile, 'default'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListAllMyBuckets
            - sts:GetCallerIdentity
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:Query
          Resource: !GetAtt RestaurantsTable.Arn

custom:
  pythonRequirements:
    layer: true
    zip: false

package:
  individually: true

functions:
  get-restaurants:
    handler: lambdas/restaurants.handler
    name: ${self:stages.${self:provider.stage}.name}-get-restaurants
    environment:
      RESTAURANTS_TABLE: ${self:stages.${self:provider.stage}.RESTAURANT_TABLE}
      default_results: 8
    events:
      - http:
          path: /restaurants
          method: get
          cors: true
    package:
      exclude:
        - '**'
      include:
        - lambdas/restaurants.py
        - lib/response.py
resources:
  Resources:
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:stages.${self:provider.stage}.RESTAURANT_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
